flask-blog/apps/controllers/apis/posts/controllers.py
# -*- coding: utf-8 -*-
from flask import Blueprint, request
from flask_login import current_user
from uuid import uuid4

from sqlalchemy import or_

from apps.common.auth import api_signin_required
from apps.common.response import ok, error
from apps.database.models import Post, Tag, Comment, View
from apps.database.session import db
from config import Config

app = Blueprint('apis_posts', __name__, url_prefix='/apis/posts')


@app.route('', methods=['GET'])
@api_signin_required
def get_posts():
    return ok()


@app.route('', methods=['POST'])
@api_signin_required
def create_post():
    return ok()


@app.route('/<int:post_id>', methods=['PUT'])
@api_signin_required
def update_post(post_id):
    form = request.form
    title = form['title']
    content = form['content']
    tags = form['tags']

    post = Post.query.filter(Post.id == post_id).first()
    if not post:
        return error(40400)
    if current_user.id != post.user_id:
        return error(40300)

    Tag.query.filter(Tag.post_id == post_id).delete()

    post.title = title
    post.content = content
    post.tags = [Tag(title=tag) for tag in tags.split(',')]
    db.session.commit()
    return ok()


@app.route('/<int:post_id>', methods=['DELETE'])
@api_signin_required
def delete_post(post_id):
    post = Post.query.filter(Post.id == post_id).first()
    if not post:
        return error(40400)
    if current_user.id != post.user_id:
        return error(40300)

    Tag.query.filter(Tag.post_id == post_id).delete()
    View.query.filter(View.post_id == post_id).delete()
    Comment.query.filter(Comment.post_id == post_id).delete()
    db.session.delete(post)
    db.session.commit()
    return ok()


@app.route('/file_upload', methods=['POST'])
@api_signin_required
def file_upload():
    args = request.args
    CKEditorFuncNum = args['CKEditorFuncNum']
    upload = request.files['upload']

    random_uuid = uuid4()
    ex = upload.filename.split('.')[1]
    upload.save('{}/media/{}.{}'.format(Config.STATIC_DIR, random_uuid, ex))
    path = '/static/media/{}.{}'.format(random_uuid, ex)
    result = '<script>window.parent.CKEDITOR.tools.callFunction("{}", "{}", "")</script>'.format(
        CKEditorFuncNum, path)
    return result


@app.route('/<int:post_id>/comments/<int:comment_id>', methods=['PUT'])
@api_signin_required
def update_comment(post_id, comment_id):
    return ok()


@app.route('/<int:post_id>/comments/<int:comment_id>', methods=['DELETE'])
@api_signin_required
def delete_comment(post_id, comment_id):
    return ok()


@app.route('/<int:post_id>/comments', methods=['POST'])
@api_signin_required
def create_comment(post_id):
    return ok()

flask-blog/apps/controllers/index/controllers.py
# -*- coding: utf-8 -*-
import re
from datetime import datetime, timedelta

from flask import Blueprint, send_from_directory, render_template, abort, request
from flask_login import current_user

from apps.common.auth import signin_required
from apps.database.models import Post, Tag, View, Comment
from apps.database.session import db
from config import Config

app = Blueprint('index', __name__, url_prefix='/')


@app.route('', methods=['GET'])
@signin_required
def index():
    args = request.args
    page = int(args.get('page') or 1)
    per_page = 3

    pagination = Post.query.order_by(Post.id.desc()).paginate(page, per_page)
    posts = pagination.items
    for post in posts:
        post.content = re.sub(r'<img.*/>', '', post.content)[:20]
    return render_template('main/index.html', posts=posts, pagination=pagination)


@app.route('/<int:post_id>', methods=['GET'])
@signin_required
def get_post(post_id):
    post = Post.query.filter(Post.id == post_id).first()
    if not post:
        abort(404)
    view = View.query.filter(View.ip_address == request.remote_addr, View.post_id == post.id,
                             View.user_id == current_user.id,
                             View.created_at > datetime.now() - timedelta(minutes=30)).first()
    if not view:
        view = View(ip_address=request.remote_addr, post_id=post.id, user_id=current_user.id)
        db.session.add(view)
        db.session.commit()
    view_cnt = View.query.filter(View.post_id == post.id).count()

    prev_post = Post.query.filter(Post.id < post_id).order_by(Post.id.desc()).first()
    next_post = Post.query.filter(Post.id > post_id).order_by(Post.id.desc()).first()

    related_posts = []
    for tag in post.tags:
        tags = Tag.query.filter(Tag.title == tag.title, Tag.post_id != post.id).order_by(Tag.id.desc()).limit(2).all()
        for t in tags:
            if not [x for x in related_posts if x.id == t.post.id]:
                t.post.thumbnail = re.search(r'<img.*/>', t.post.content)
                t.post.thumbnail = t.post.thumbnail.group() if t.post.thumbnail else None
                t.post.content = re.sub(r'<img.*/>', '', t.post.content)[:20]
                related_posts.append(t.post)
    related_posts = related_posts[:6]

    comments = Comment.query.filter(Comment.post_id == post.id, Comment.parent_id == None).all()
    for comment in comments:
        comment.comments = Comment.query.filter(Comment.parent_id == comment.id).all()
    return render_template('main/post.html', post=post, prev_post=prev_post, next_post=next_post,
                           related_posts=related_posts, view_cnt=view_cnt, comments=comments)


@app.route('/<int:post_id>/update', methods=['GET'])
@signin_required
def update(post_id):
    post = Post.query.filter(Post.id == post_id).first()
    if not post:
        abort(404)
    return render_template('main/update.html', post=post)


@app.route('/about', methods=['GET'])
@signin_required
def about():
    return render_template('main/about.html')


@app.route('/create', methods=['GET'])
@signin_required
def create():
    return render_template('main/create.html')


@app.route('favicon.ico')
def favicon():
    return send_from_directory(Config.STATIC_DIR, 'favicon.ico', mimetype='image/vnd.microsoft.icon')

flask-blog/templates/layout/base.html
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" charset="utf-8"/>
  <link rel="stylesheet" type="text/css" href="/static/css/style.css"/>
  <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/js/bootstrap/bootstrap.min.js"></script>
  <script>
    $(function() {
      $("#search > input").on("keyup", function() {
        $.ajax({
          url: "{{ url_for('apis_posts.get_posts') }}?q=" + $(this).val(),
          type: "GET",
          success: function(data) {
            $("#search-result").html("");
            for(let post of data.data) {
              $("#search-result").append(`<li><a href="/${post.id}">${post.title}</a></li>`)
            }
          },
          error(xhr) {
            alert(`${xhr.status} / ${xhr.responseJSON['message']}`);
          }
        });
      });
    });

    function goToURL(url) {
      location.href = url;
    }

    function showSearch() {
      $('#search').css({'display': 'block'});
      $('#search > input').focus();
    }

    function hideSearch() {
      $('#search').css({'display': 'none'});
    }
  </script>
  {% block head %}
  {% endblock %}
</head>
<body>
  {% import 'layout/pagination.html' as macros %}
  {% block body %}
  {% endblock %}
  {% block script %}
  {% endblock %}
</body>
</html>

flask-blog/templates/layout/pagination.html
{% macro pagination_index(pagination, endpoint) %}
  <div id="main-pagination">
    {% for p in pagination.iter_pages() %}
      {% if p %}
        {% if p == pagination.page %}
          <em>{{ p }}</em>
        {% else %}
          <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
        {% endif %}
      {% else %}
        <a>...</a>
      {% endif %}
    {% endfor %}
  </div>
{% endmacro %}

flask-blog/templates/layout/sidebar.html
<div id="sidebar">
  <div id="sidebar-profile">
    <a href="{{ url_for('index.index') }}"><img src="/static/image/profile.png" id="sidebar-profile-img"></a>
    <p id="sidebar-profile-text">
      플라스크 블로그
    </p>
  </div>
  <div id="sidebar-icon">
    <a href="/">
      <i class="fa fa-home fa-2x" aria-hidden="true"></i>
    </a>
    <a href="{{ url_for('index.about') }}">
      <i class="fa fa-user fa-2x" aria-hidden="true"></i>
    </a>
    <a href="{{ url_for('index.create') }}">
      <i class="fa fa-edit fa-2x" aria-hidden="true"></i>
    </a>
    <a onclick="showSearch();" style="cursor: pointer;">
      <i class="fa fa-search fa-2x" aria-hidden="true"></i>
    </a>
    <div id="search" style="display: none">
      <input>
      <i class="fa fa-times fa-1x" aria-hidden="true" onclick="hideSearch();"></i>
      <ul id="search-result"></ul>
    </div>
  </div>
</div>