flask-movie/apps/controllers/movies/controllers.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template

from apps.common.auth import signin_required
from apps.database.models import Movie

app = Blueprint('movies', __name__, url_prefix='/movies')


@app.route('', methods=['GET'])
@signin_required
def index():
    return ''

flask-movie/apps/controllers/users/controllers.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user, logout_user

from apps.common.auth import SHA256, already_signin
from apps.controllers.users.forms import SignInForm, SignUpForm
from apps.database.models import User
from apps.database.session import db

app = Blueprint('users', __name__, url_prefix='/users')


@app.route('/signup', methods=['GET', 'POST'])
@already_signin
def signup():
    return ''


@app.route('/signin', methods=['GET', 'POST'])
@already_signin
def signin():
    return ''


@app.route('signout', methods=['GET'])
def signout():
    return ''

flask-movie/templates/layout/base.html
<!doctype html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" charset="utf-8"/>
  <link rel="stylesheet" type="text/css" href="/static/css/style.css"/>
  <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.min.css"/>
  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/js/bootstrap/bootstrap.min.js"></script>
  {% block head %}
  {% endblock %}
</head>
<body>
  {% block body %}
  {% endblock %}
  {% block script %}
  {% endblock %}
</body>

flask-movie/templates/layout/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <a class="navbar-brand" href="{{ url_for('showtimes.index') }}">영화관</a>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('movies.index') }}">영화</a>
      </li>
    </ul>
  </div>

  <div class="nav-item dropdown">
    <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      {{ current_user.nickname }}
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
      <a class="dropdown-item" href="{{ url_for('users.signout') }}">signout</a>
    </div>
  </div>
</nav>