flask-shop/apps/controllers/apis/products/__init__.py
# -*- coding: utf-8 -*-

flask-shop/apps/controllers/apis/products/controllers.py
from flask import Blueprint, request

from apps.common.response import ok
from apps.database.models import Product

app = Blueprint('apis_products', __name__, url_prefix='/apis/products')


@app.route('', methods=['GET'])
def products():
    return ok()

flask-shop/apps/controllers/carts/controllers.py
from flask import Blueprint, render_template

from apps.common.auth import signin_required
from apps.controllers.carts import get_carts
from apps.controllers.orders import get_orders
from apps.database.models import Category

app = Blueprint('carts', __name__, url_prefix='/carts')


@app.route('', methods=['GET'])
@signin_required
def index():
    categories = Category.query.all()
    return render_template('carts/index.html', carts=get_carts(), categories=categories, orders=get_orders())

flask-shop/apps/controllers/orders/controllers.py
from flask import Blueprint, render_template

from apps.common.auth import signin_required
from apps.controllers.carts import get_carts
from apps.controllers.orders import get_orders
from apps.database.models import Category

app = Blueprint('orders', __name__, url_prefix='/orders')


@app.route('', methods=['GET'])
@signin_required
def index():
    categories = Category.query.all()
    return render_template('orders/index.html', carts=get_carts(), categories=categories, orders=get_orders())

flask-shop/apps/controllers/products/__init__.py
# -*- coding: utf-8 -*-

flask-shop/apps/controllers/products/controllers.py
from flask import Blueprint, render_template

from apps.controllers.carts import get_carts
from apps.controllers.orders import get_orders
from apps.database.models import Category, Product

app = Blueprint('product', __name__, url_prefix='/products')


@app.route('/<int:product_id>', methods=['GET'])
def get_product(product_id):
    categories = Category.query.all()
    product = Product.query.filter(Product.id == product_id).first()
    return render_template('product/detail.html', categories=categories, product=product, orders=get_orders(), carts=get_carts())

flask-shop/templates/product/detail.html
{% extends 'layout/base.html' %}

{% block head %}
  <title>flask shop</title>
{% endblock %}

{% block body %}
  {% include 'layout/header.html' %}

  <div class="container pt-4">
    <div class="row">
      <div class="col-lg-4">
        <img src="{{ product.image_url }}" class="card-img-top" alt="">
      </div>
      <div class="col-lg-4">
      </div>
      <div class="col-lg-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text"></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">{{'{:,}'.format(product.price)}}원</li>
          </ul>
          <div class="card-body">
            <a href="#" class="card-link" onclick="buy()">구매하기</a>
            <a href="#" class="card-link" onclick="addCart()">장바구니</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block script %}
  <script>
    function buy() {
      let data = {
        'product_ids': [{{ product.id }}],
        'product_cnt': [1],
      };
      data.product_ids = data.product_ids.join(',');
      data.product_cnt = data.product_cnt.join(',');
      $.ajax({
        url: `{{ url_for('apis_orders.create_order') }}`,
        type: "POST",
        data: data,
        success: function(data) {
          window.location.href = "{{ url_for('orders.index') }}"
        },
        error(xhr) {
          alert(`${xhr.status} / ${xhr.responseJSON['message']}`);
        }
      });
    }

    function addCart() {
      const data = {product_id: "{{ product.id }}"};
      $.ajax({
        url: `{{ url_for('apis_carts.create_cart') }}`,
        type: "POST",
        data: data,
        success: function(data) {
          if(confirm('장바구니에 추가되었습니다. 장바구니로 이동하시겠습니까?')) {
            window.location.href = "{{ url_for('carts.index') }}";
          }
        },
        error(xhr) {
          window.location.href = "{{ url_for('users.signin') }}";
        }
      });
    }
  </script>
{% endblock %}