flask-movie/apps/controllers/cinemas/__init__.py
# -*- coding: utf-8 -*-

flask-movie/apps/controllers/cinemas/controllers.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, request

from apps.common.auth import signin_required
from apps.database.models import Cinema

app = Blueprint('cinemas', __name__, url_prefix='/cinemas')


@app.route('', methods=['GET'])
@signin_required
def index():
    return ''

flask-movie/apps/controllers/showtimes/controllers.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, request
from datetime import datetime, timedelta

from sqlalchemy import and_

from apps.common.auth import signin_required
from apps.database.models import Showtime, Movie, TheaterTicket, Theater

app = Blueprint('showtimes', __name__, url_prefix='/showtimes')


@app.route('', methods=['GET'])
@signin_required
def index():
    return ''

flask-movie/templates/cinemas/index.html
{% extends 'layout/base.html' %}

{% block head %}
  <title>cinema</title>
{% endblock %}

{% block body %}
  <div class="container">
    {% include('layout/nav.html') %}
    <div class="card-group">
      {% for cinema in cinemas %}
        <div class="card" style="">
          <img class="card-img-top" src="{{ cinema.image_url }}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">{{ cinema.title }}</h5>
            <p class="card-text">{{ cinema.address }} {{ cinema.detail_address }}</p>
          </div>
          <div class="card-body">
            <a href="{{ url_for('showtimes.index', movie_id=movie_id, cinema_id=cinema.id) }}" class="card-link btn btn-primary">예매하기</a>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}